#1 Add an initial version of services API
secs-dev/itmo-dating pull request #5
Opened 2024-09-20 13:48 UTC by vityaman

2024-09-20 14:28 UTC, e1turin approved these changes

2024-09-20 16:12 UTC, Kimiega requested changes

2024-09-20 16:12 UTC, Kimiega commented on people/api/src/main/resources/static/openapi/api.yml
> +        200:
400ка, body неправильно заполнено может быть

2024-09-20 16:12 UTC, Kimiega commented on people/api/src/main/resources/static/openapi/api.yml
> +      responses:
Также 400ку стоит добавить

2024-09-20 16:12 UTC, Kimiega commented on people/api/src/main/resources/static/openapi/api.yml
> +      example: Ivan
Не матчится с паттерном заглавная буква

2024-09-20 16:12 UTC, Kimiega commented on people/api/src/main/resources/static/openapi/api.yml
> +    PictureUrl:
Ручку на загрузку фото думаю стоит еще добавить

2024-09-20 16:15 UTC, vityaman commented on matchmaker/api/src/main/resources/static/openapi/api.yml
> +  schemas:
Это буквально GeneralError

2024-09-20 16:16 UTC, vityaman commented on matchmaker/api/src/main/resources/static/openapi/api.yml
> +  /people/{person_id}/matches:
Надо бы

2024-09-20 16:18 UTC, vityaman commented on people/api/src/main/resources/static/openapi/api.yml
> +        - name: limit
Точняк, надо добавить `maximum` в схему. Я бы выдал типа 64 - наверное, пойдет. Дефолт не знаю, как указать, мб в description.

2024-09-20 16:21 UTC, vityaman commented on people/api/src/main/resources/static/openapi/api.yml
> +        - name: radius_meters
Давай

2024-09-20 16:21 UTC, vityaman commented on people/api/src/main/resources/static/openapi/api.yml
> +          description: Minimum birthday of a person
Ой, да, это для фильтрации по `update_moment`

2024-09-20 16:21 UTC, vityaman commented on people/api/src/main/resources/static/openapi/api.yml
> +        200:
Да тут полно таких 400к может быть.

2024-09-20 16:21 UTC, vityaman commented on people/api/src/main/resources/static/openapi/api.yml
> +        200:
Да

2024-09-20 16:21 UTC, vityaman commented on people/api/src/main/resources/static/openapi/api.yml
> +      responses:
Да

2024-09-20 16:21 UTC, vityaman commented on people/api/src/main/resources/static/openapi/api.yml
> +      example: Ivan
Точняк, надо подредачить

2024-09-20 16:21 UTC, vityaman commented on people/api/src/main/resources/static/openapi/api.yml
> +    PictureUrl:
Стоит. Звучит, как третий сервис) Ну, го сюда добавим.

2024-09-21 02:01 UTC, Kimiega commented on matchmaker/api/src/main/resources/static/openapi/api.yml
> +  schemas:
Решили выкинуть

2024-09-21 04:21 UTC, vityaman commented
@Kimiega, го вольем это.

2024-09-21 07:07 UTC, vityaman commented on people/api/src/main/resources/static/openapi/api.yml
> +    PictureUrl:
Записал в туду лист, будет сделано.

2024-09-21 07:07 UTC, merged