#45 Setup JOOQ and R2DBC foundation
secs-dev/itmo-dating pull request #53
Opened 2024-11-11 15:36 UTC by vityaman

2024-11-11 16:14 UTC, Kimiega requested changes

2024-11-11 16:14 UTC, Kimiega commented on backend/foundation/src/main/kotlin/ru/ifmo/se/dating/spring/SpringTxEnv.kt
> +    override fun <T : Any> transactional(flow: Flow<T>): Flow<T> =
На столько не доверяешь спрингу?

2024-11-11 16:14 UTC, Kimiega commented on backend/foundation/src/main/kotlin/ru/ifmo/se/dating/text/Abbreviate.kt
> +fun String.abbreviated(maxLength: Int = 16): String =
Давай 16 константой вынесем?)

2024-11-11 16:14 UTC, Kimiega commented on backend/people/src/main/kotlin/ru/ifmo/se/dating/people/api/HttpPeopleApi.kt
> +    override suspend fun peoplePersonIdDelete(personId: Long): ResponseEntity<Unit> =
А нам точно везде `suspend` нужен? Почему спринг с этим не справляется?

2024-11-11 16:14 UTC, Kimiega commented on backend/people/src/main/resources/database/changelog.sql
> +CREATE SCHEMA people;
Вообще, я бы основной changelog сделал yml, а затем по пакетам разные фичи разделял, плюс добавлял в название дату и номер изменения, в самих пакетах sql оставить можно, просто инклюдить их

2024-11-11 16:14 UTC, Kimiega commented on itmo-dating.iml
Почему?(

2024-11-11 16:18 UTC, vityaman commented on backend/people/src/main/kotlin/ru/ifmo/se/dating/people/api/HttpPeopleApi.kt
> +    override suspend fun peoplePersonIdDelete(personId: Long): ResponseEntity<Unit> =
Потому что на реакторе исполняется, нужна корутина.

2024-11-11 16:19 UTC, vityaman commented on backend/people/src/main/resources/database/changelog.sql
> +CREATE SCHEMA people;
А зачем?

2024-11-11 16:20 UTC, vityaman commented on itmo-dating.iml
Я открыл директорию в идее, она не дала подсказок, из чего я сделал вывод, что эта штука ничего не делает.

2024-11-11 16:28 UTC, Kimiega commented on backend/people/src/main/resources/database/changelog.sql
> +CREATE SCHEMA people;
Так мы фичи ликвибейза не будем полностью использовать

2024-11-11 16:29 UTC, Kimiega commented on itmo-dating.iml
Руками импортнуть как модуль надо этот файл

2024-11-11 16:30 UTC, vityaman commented on backend/people/src/main/resources/database/changelog.sql
> +CREATE SCHEMA people;
А мне для жука как будто нужен один sql файл -- вот в чем дело. Ну, я посмотрю завтра.

2024-11-11 16:30 UTC, vityaman commented on itmo-dating.iml
Окей, верну и попробую так.

2024-11-12 05:20 UTC, vityaman commented on backend/foundation/src/main/kotlin/ru/ifmo/se/dating/text/Abbreviate.kt
> +fun String.abbreviated(maxLength: Int = 16): String =
Ок, но зачем? Никто эту константу не увидит больше.

2024-11-12 05:21 UTC, vityaman commented on backend/people/src/main/resources/database/changelog.sql
> +CREATE SCHEMA people;
Тестконтейнер принимает только один файл в качестве инитскрипта, потому оставляю так.

2024-11-12 05:28 UTC, vityaman commented on itmo-dating.iml
Короче, у меня не заработало. Давай ты в гитигнор его закинешь и себе добавишь.

2024-11-12 05:40 UTC, merged